---
site:
  title: "Securing RHEL Image Mode: Firewall Rules at Build Time"
  url: https://github.com/rhpds/image-mode-security-firewall
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www
