---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
    - name: module-01-intro
      label: "Introduction to Firewall Rules in Image Mode"
      solveButton: false
    - name: module-02-runtime-firewall-rules
      label: "Applying Firewall Rules on a Running Host"
      solveButton: false
    - name: module-03-build-time-firewall-rules
      label: "Baking Firewall Rules into the Containerfile"
      solveButton: false
    - name: conclusion
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "Build host terminal"
    path: /wetty/ssh/root
    port: 443
  - name: ">_ Bootc VM"
    path: /wetty_bootc_vm/ssh/root
    port: 443
    modules:
      - module-02-runtime-firewall-rules
      - module-03-build-time-firewall-rules
