---
namespace: "image_mode_security_firewall"
name: "automation"
version: "1.0.0"
readme: README.md
authors:
  - "nlager <nlager@redhat.com>"
description: "Starter collection for this project's custom Ansible automation."
license: []
repository: "https://github.com/rhpds/image-mode-security-firewall"
